### ISSUE TITLE
Смесь библиотек

### ISSUE THREAD

**Issue by AlexZabashta** [MLFreelib/cvflow#15]
https://github.com/MLFreelib/cvflow/blob/b7e37aa55ee67f1176d0f333f2ee614e07a348cf/common/ctc_decoder.py#L3

На первый взгляд Торч импортируется, но нигде не используется. Я так понял используются тензоры полученные из Торча, но тогда зачем их перегонять в Нумпай, если тот же logsumexp есть и в Торче.

**Comment by egorkrash** [comment]
Декодинг для CRNN в любом случае нормально не параллелится, так что не принципиально использовать торч. Убрал импорт.
