### ISSUE TITLE
Значения по умолчанию

### ISSUE THREAD

**Issue by AlexZabashta** [MLFreelib/cvflow#16]
https://github.com/MLFreelib/cvflow/blob/b7e37aa55ee67f1176d0f333f2ee614e07a348cf/common/prepare_plates_data.py#L8

Я так понял, так задаётся знание по умолчанию. Почему не используется соответствующий аргумент `default` из библиотеки **ArgumentParser**?

**Comment by egorkrash** [comment]
Fixed here https://github.com/MLFreelib/cvflow/commit/3fd893e21d2a80d6a21e6da519e30827af7c5e2b
