### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by AlexZabashta** [MLFreelib/cvflow#17]
https://github.com/MLFreelib/cvflow/blob/b7e37aa55ee67f1176d0f333f2ee614e07a348cf/gui/roi_getter.py#L68-L70

В таких местах лучше использовать специальный модуль `json`, который сам приведёт объект к json-строке.

**Comment by s70c3** [comment]
Так как это не JSON, а другой формат конфигурации, то исправлено с помощью использования сериализации в configparser.
