### ISSUE TITLE
Извлечение тензора ради размера

### ISSUE THREAD

**Issue by AlexZabashta** [MLFreelib/cvflow#18]
https://github.com/MLFreelib/cvflow/blob/b7e37aa55ee67f1176d0f333f2ee614e07a348cf/components/handler_component.py#L125

Зачем извлекать целый тензор ради того, чтобы узнать его размер. Почему соответствующая функция `torch.Tensor.size` для этого не подходит?

**Comment by szymanski52** [comment]
Исправил:
```
if meta_frame.get_meta_info(MetaName.META_BBOX.value) is not None:
    self.__update(meta_frame.get_meta_info(MetaName.META_BBOX.value),
                  meta_frame.get_frame().size, src_name)
                
```
