### ISSUE TITLE
Некорректное сообщение об ошибке cuda/cpu

### ISSUE THREAD

**Issue by s70c3** [MLFreelib/cvflow#28]
При указании значении ключа -d cuda  при условии, если в устройстве нет GPU выводится некорректное сообщение об ошибке, не имеющее смысла:

```TypeError: Expected cuda or cpu, actual cuda```

Предложение:

Проверять наличие GPU отдельно и выводить соответствующее сообщение об ошибке.

**Comment by paNoNi** [comment]
Добавлено оповещение при выборе cuda, если cuda при этом не доступна. Также устройство автоматически переводится в cpu.
